# Inferencing
## Import Libraries

In [11]:
# import libraries
import pickle
import pandas as pd
import numpy as np
from utils import cardinality
from sklearn.preprocessing import FunctionTransformer

## Load Model

In [12]:
# load model 
with open('pipeline.pkl', 'rb') as file:
    pipeline = pickle.load(file)

## Define User

In [13]:
# define user 1
user_1 = {
    'age': 21,
    'job': 'student',	
    'marital': 'single',	
    'education': 'unknown',	
    'default': 'no',	
    'balance': 109,
    'housing': 'no',
    'loan': 'no',
    'contact': 'unknown',
    'day': 27,
    'month': 8,
    'campaign': 5,
    'pdays': 103,
    'previous': 6,
    'poutcome': 'failure'
}

# define user 2
user_2 = {
    'age': 60,
    'job': 'retire',	
    'marital': 'married',	
    'education': 'tertiary',	
    'default': 'yes',	
    'balance': 50500,
    'housing': 'yes',
    'loan': 'no',
    'contact': 'telephone',
    'day': 20,
    'month': 3,
    'campaign': 5,
    'pdays': 7,
    'previous': 5,
    'poutcome': 'success'
}

# define user 3
user_3 = {
    'age': 30,
    'job': 'entrepreneur',	
    'marital': 'married',	
    'education': 'secondary',	
    'default': 'yes',	
    'balance': 70570,
    'housing': 'yes',
    'loan': 'yes',
    'contact': 'unknown',
    'day': 30,
    'month': 12,
    'campaign': 2,
    'pdays': 10,
    'previous': 3,
    'poutcome': 'other'
}

# masukkan ke dataframe
df_inf = pd.DataFrame([user_1, user_2, user_3])
df_inf

,age,job,marital,education,default,balance,housing,loan,contact,day,month,campaign,pdays,previous,poutcome
0,21,student,single,unknown,no,109,no,no,unknown,27,8,5,103,6,failure
1,60,retire,married,tertiary,yes,50500,yes,no,telephone,20,3,5,7,5,success
2,30,entrepreneur,married,secondary,yes,70570,yes,yes,unknown,30,12,2,10,3,other

## Prediction Result

In [14]:
# predict y
y_pred_inf = pipeline.predict(df_inf)
y_proba_inf = pipeline.predict_proba(df_inf)[:,1]

result = df_inf.copy()
result['prediction'] = y_pred_inf
result['prediction_label'] = result['prediction'].map({0:'Will not subscribe', 1:'Will subscribe'})
result['probability'] = y_proba_inf.round(3)

result

c:\Users\DELL\miniconda3\envs\h8_env\lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
c:\Users\DELL\miniconda3\envs\h8_env\lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

,age,job,marital,education,default,balance,housing,loan,contact,day,month,campaign,pdays,previous,poutcome,prediction,prediction_label,probability
0,21,student,single,unknown,no,109,no,no,unknown,27,8,5,103,6,failure,0,Will not subscribe,0.477
1,60,retire,married,tertiary,yes,50500,yes,no,telephone,20,3,5,7,5,success,1,Will subscribe,0.851
2,30,entrepreneur,married,secondary,yes,70570,yes,yes,unknown,30,12,2,10,3,other,1,Will subscribe,0.715